### ISSUE TITLE
What's the use of accessory information in the examples?

### ISSUE THREAD

**Issue by marcinruszkiewicz** [karlentwistle/ruby_home#71]
I mean this line:

`accessory_information = RubyHome::ServiceFactory.create(:accessory_information)`

What's it supposed to do? It's not really used anywhere else in any of the examples, and if I comment it in my own sensor implementation it doesn't really change anything.

Also, is there any other way to get to which service has which characteristics available other than doing `sensor = RubyHome::ServiceFactory.create(:temperature_sensor)` and then calling `sensor.characteristics` and going through it?

**Comment by karlentwistle** [comment]
Hey @marcinruszkiewicz thanks for your questions.

> What's it supposed to do? It's not really used anywhere else in any of the examples, and if I comment it in my own sensor implementation it doesn't really change anything.

Strictly speaking, none of the examples require the line:

```ruby
accessory_information = RubyHome::ServiceFactory.create(:accessory_information)
```

This is because they only showcase one service per file. The reason I've included it is because it is required if you want to expose two services at once. For example:

```ruby
accessory_information = RubyHome::ServiceFactory.create(:accessory_information)
fan = RubyHome::ServiceFactory.create(:fan)
lightbulb = RubyHome::ServiceFactory.create(:lightbulb)
```

I thought it would be better to include them in the examples so it doesn't catch anyone by surprise if they try and expand on one of the examples to offer multiple services.

I'll update the README to try an explain this better.

> Also, is there any other way to get to which service has which characteristics available other than doing sensor = RubyHome::ServiceFactory.create(:temperature_sensor) and then calling sensor.characteristics and going through it?

Currently, there isn't. However, my plan is to document all the different services RubyHome / Apple officially support within the examples directory this can serve as a form of documentation to see all the characteristics a service offers.
