### ISSUE TITLE
TV device

### ISSUE THREAD

**Issue by FWMatt** [karlentwistle/ruby_home#98]
Hi,

I've noticed that HomeBridge has a "TV" device defined (via a plugin). Any plans to do that for RubyHome? Can I help to add it if not?

Thank you!
Matt

**Comment by jeffmcfadden** [comment]
I'm not a maintainer here, but from what I can tell from the HomeKit docs, there aren't any services types or characteristics in the HomeKit platform that would explicitly support a TV device, so the best you could do would be to use a switch type (or similar) to control the basic on/off features, and maybe try to fake a channel selection with a thermostat or something like that.

Do you know how the TV device from HomeBridge appears in the Home app? How does it present itself?

**Comment by FWMatt** [comment]
I’ve also been doing some research - I’m not sure this device type is released yet. When it is you should be able to switch on / off as you say, but also control volume, inputs and channel. 

https://www.imore.com/airplay-homekit-smart-tv
(No technical info here I’m afraid)

**Comment by karlentwistle** [comment]
Hey @FWMatt 

Firstly sorry for the belated response. I meant to respond to you sooner. Since I wrote this library, my daughter was born, so I've had slightly less free time outside of work for coding and open source. 😄 

I had a look into this today. Unfortunately, Apple hasn't updated the [Homekit Specification](https://developer.apple.com/homekit/) to document exactly how a TV service is supposed to be work. As you say this is already a feature in HomeBridge and it seems like the TV accessory is defined within https://github.com/homebridge/HAP-NodeJS/blob/master/src/accessories/TV_accessory.ts

Having a quick look through their code, it seems that we'd need a few new [services.yml](https://github.com/karlentwistle/ruby_home/blob/master/lib/ruby_home/config/services.yml) and [characteristics](https://github.com/karlentwistle/ruby_home/blob/master/lib/ruby_home/config/characteristics.yml) to support television.

Firstly we'd need a new service defined in the services.yml file for the "television" itself. For example:

```YAML
# lib/ruby_home/config/services.yml
- :name: :television
  :description: Television
  :uuid: '000000D8-0000-1000-8000-0026BB765291'
  :optional_characteristics_uuids:
  - 00000008-0000-1000-8000-0026BB765291
  - # etc
  :required_characteristics_uuids:
  - 000000B0-0000-1000-8000-0026BB765291
  - 000000E7-0000-1000-8000-0026BB765291
  - 000000E3-0000-1000-8000-0026BB765291
  - 000000E1-0000-1000-8000-0026BB765291
  - 000000E8-0000-1000-8000-0026BB765291
```

Now if we take one of these characteristic UUIDs as an example. `000000B0-0000-1000-8000-0026BB765291` this one refers to the "active" characteristic. This one [already happens to be defined](https://github.com/karlentwistle/ruby_home/blob/402514f85d889219382e3d448956765820b72b0b/lib/ruby_home/config/characteristics.yml#L18) so should "just work".

Sadly not all the characteristics are ones that are imported with [my automated script](https://github.com/karlentwistle/ruby_home/blob/master/sbin/characteristic_generator.rb). So we'd need to define the missing ones manually. 😱 This would be a case of cross-referencing them against [HAP-NodeJS](https://github.com/homebridge/HAP-NodeJS/blob/eab77bfecde1813c136b3732a1989f03c54f65e4/src/lib/gen/HomeKit-TV.ts#L513-L534).

The characteristics.yml would then end up having a bunch of these appended:

```YAML
# lib/ruby_home/config/characteristics.yml
- :name: :active_Identifier
  :description: Active Identifier
  :uuid: 000000E7-0000-1000-8000-0026BB765291
  :format: uint32
  :unit: nil
  :permissions:
  - securedRead
  :properties:
  - read
  - write
  - cnotify
  :constraints:
- :name: :configured_name
  :description: Configured Name
  :uuid: 000000E3-0000-1000-8000-0026BB765291
  :format: string
  :unit: nil
  :permissions:
  - securedRead
  :properties:
  - read
  - write
  - cnotify
  :constraints:
# etc
``` 

After the service and characters are input into the YAML files, we'd be able to use them like this:

```ruby
television = RubyHome::ServiceFactory.create(:television,
  active: 0, # required
  # etc
)
```

Looking through https://github.com/homebridge/HAP-NodeJS/blob/master/src/accessories/TV_accessory.ts it seems like "television" isn't only new service we'd require. I think we'd also need:

- [InputSource](https://github.com/homebridge/HAP-NodeJS/blob/eab77bfecde1813c136b3732a1989f03c54f65e4/src/lib/gen/HomeKit-TV.ts#L513-L534) (Seems like you need one of these for each HDMI input)
- [TelevisionSpeaker](https://github.com/homebridge/HAP-NodeJS/blob/eab77bfecde1813c136b3732a1989f03c54f65e4/src/lib/gen/HomeKit-TV.ts#L542-L558) (I think this one might be optional though)

Those two services would also need to be added to the `lib/ruby_home/config/services.yml` file and then each of their characteristics would need to be added into `lib/ruby_home/config/characteristics.yml`.

Then to compose the entire accessory, I think it would end up looking something like this:

```ruby
television = RubyHome::ServiceFactory.create(:television,
  active: 0, # required
  # etc
)

hdmi1 = RubyHome::ServiceFactory.create(:input_source,
  configured_name: "HDMI 1", # required
  # etc
)
```

> Can I help to add it if not?

If you're interested in working on these changes within RubyHome I'd gladly set aside some time to answer questions/review/test and merge a PR.

If you have any more questions I will try and respond more quickly than 27 days 😅
